name: publish upm

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.1

      - name: Create UPM Branches
        uses: hecomi/create-upm-branch-action@main
        with:
          git-tag: echo ${{steps.tag.outputs.tag}}
          pkg-root-dir-path: Packages/AuthGate
